services:
  tensorrt-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtdetr-v2-trt
    environment:
      - DISPLAY
    devices:
      - "/dev/video0:/dev/video0"     
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: bash